<div class="content" role="main">
  <h1>Throwing and returning</h1>

  <div class="card card--headed">
    <div class="header">Some other details</div>
    <ul>
      <li><code>return</code> is used to set the value when <code>{{ '{' }} done: true }</code></li>
      <li>The return value, however, isn't included when iterating using spread, or for...of</li>
      <li>Throwing an exception inside a generator will return that error on <code>next()</code></li>
      <li>...and will complete the generator</li>
    </ul>

    <app-console>
      <pre>function* myGenerator() {{ '{' }}</pre>
      <pre>  throw new Error('Oops...');</pre>
      <pre>}</pre>
      <pre>

      </pre>
      <pre>const generator = myGenerator();</pre>
      <pre>

      </pre>

      <pre>generator.next(); <span class="comment">// Uncaught Error: Oops...</span></pre>
    </app-console>
  </div>
</div>
